package dice

import (
	"fmt"
	"math/rand"
	"sort"
)

// maxExplodeDepth bounds the number of explosions a single
// ModExplodeCompound pass may produce, guarding against runaway
// chains under adversarial or degenerate RNG output (e.g., a d1
// where every roll is the max). The cap counts only the new dice
// generated by explosions, not the initial roll batch, so legitimate
// large rolls (e.g., 5000d100!!) aren't artificially limited.
const maxExplodeDepth = 1000

// EvaluateSingle runs the full evaluation pipeline on a parsed Expression.
// Multi-roll orchestration lives in multiroll.go.
func EvaluateSingle(rng *rand.Rand, expr Expression) (Result, error) {
	// ------------------------------------------------------------
	// 1. INITIAL ROLLS
	// ------------------------------------------------------------
	rolls := make([]int, expr.Count)
	for i := 0; i < expr.Count; i++ {
		rolls[i] = rng.Intn(expr.Sides) + 1
	}

	var (
		rerolls  []int
		exploded []int
	)

	// ------------------------------------------------------------
	// 2. REROLL PASS
	// ------------------------------------------------------------
	rerollReplaceApplied := false
	rerollOnceApplied := false
	rerollAddApplied := false

	for _, mod := range expr.Modifiers {
		switch mod.Kind {

		case ModReroll:
			if !rerollReplaceApplied {
				rolls, rerolls = doRerollReplace(rng, rolls, expr.Sides, mod.Threshold, rerolls)
				rerollReplaceApplied = true
			}

		case ModRerollOnce:
			if !rerollOnceApplied {
				rolls, rerolls = doRerollOnce(rng, rolls, expr.Sides, mod.Threshold, rerolls)
				rerollOnceApplied = true
			}

		case ModRerollAdd:
			if !rerollAddApplied {
				rolls, rerolls = doRerollAdd(rng, rolls, expr.Sides, mod.Threshold, rerolls)
				rerollAddApplied = true
			}
		}
	}

	// Freeze post-reroll state for result reporting
	postReroll := append([]int(nil), rolls...)

	// ------------------------------------------------------------
	// 3. EXPLODING PASS
	// ------------------------------------------------------------
	for _, mod := range expr.Modifiers {
		switch mod.Kind {
		case ModExplode:
			rolls, exploded = doExplodeSimple(rng, rolls, expr.Sides, exploded)
		case ModExplodeThreshold:
			rolls, exploded = doExplodeThreshold(rng, rolls, expr.Sides, mod.Threshold, exploded)
		case ModExplodeCompound:
			var err error
			rolls, exploded, err = doExplodeCompound(rng, rolls, expr.Sides, exploded)
			if err != nil {
				return Result{}, err
			}
		}
	}

	// ------------------------------------------------------------
	// 4. KEEP/DROP PASS
	// ------------------------------------------------------------
	kept := append([]int(nil), rolls...)
	var dropped []int

	for _, mod := range expr.Modifiers {
		switch mod.Kind {
		case ModKeepHigh:
			kept, dropped = keepHighest(kept, mod.Count)
		case ModKeepLow:
			kept, dropped = keepLowest(kept, mod.Count)
		case ModDropHigh:
			kept, dropped = dropHighest(kept, mod.Count)
		case ModDropLow:
			kept, dropped = dropLowest(kept, mod.Count)
		}
	}

	// ------------------------------------------------------------
	// 5. TOTAL
	// ------------------------------------------------------------
	// Total is just the sum of kept values. Arithmetic (+N, *N, etc.)
	// is the AST evaluator's responsibility (see eval_ast.go::
	// combineBinaryResults); any ModAdditive entries that reach this
	// function are silently ignored.
	total := 0
	for _, v := range kept {
		total += v
	}
	// ------------------------------------------------------------
	// 6. SUCCESS THRESHOLDS
	// ------------------------------------------------------------
	successes := 0
	for _, mod := range expr.Modifiers {
		if mod.Kind == ModSuccessThreshold {
			successes = countSuccesses(kept, mod.Op, mod.Value)
			break
		}
	}

	// ------------------------------------------------------------
	// 7. BUILD RESULT
	// ------------------------------------------------------------
	return Result{
		Expression: expr.Raw,
		Rolls:      postReroll,
		Rerolls:    rerolls,
		Exploded:   exploded,
		Kept:       kept,
		Dropped:    dropped,
		Total:      total,
		Successes:  successes,
	}, nil
}

//
// REROLL HELPERS
//

func doRerollReplace(rng *rand.Rand, rolls []int, sides, threshold int, existing []int) ([]int, []int) {
	rerolls := existing
	for i, v := range rolls {
		if v <= threshold {
			rerolls = append(rerolls, v)
			rolls[i] = rng.Intn(sides) + 1
		}
	}
	return rolls, rerolls
}

func doRerollOnce(rng *rand.Rand, rolls []int, sides, threshold int, existing []int) ([]int, []int) {
	rerolls := existing
	for i, v := range rolls {
		if v <= threshold {
			newVal := rng.Intn(sides) + 1
			rerolls = append(rerolls, newVal)
			rolls[i] = newVal
		}
	}
	return rolls, rerolls
}

func doRerollAdd(rng *rand.Rand, rolls []int, sides, threshold int, existing []int) ([]int, []int) {
	rerolls := existing
	out := rolls
	for _, v := range rolls {
		if v <= threshold {
			newVal := rng.Intn(sides) + 1
			rerolls = append(rerolls, newVal)
			out = append(out, newVal)
		}
	}
	return out, rerolls
}

//
// EXPLODE HELPERS
//

func doExplodeSimple(rng *rand.Rand, rolls []int, sides int, acc []int) ([]int, []int) {
	out := append([]int(nil), rolls...)
	for _, v := range rolls {
		if v == sides {
			newv := rng.Intn(sides) + 1
			acc = append(acc, newv)
			out = append(out, newv)
		}
	}
	return out, acc
}

func doExplodeThreshold(rng *rand.Rand, rolls []int, sides int, threshold int, acc []int) ([]int, []int) {
	out := append([]int(nil), rolls...)
	for _, v := range rolls {
		if v >= threshold {
			newv := rng.Intn(sides) + 1
			acc = append(acc, newv)
			out = append(out, newv)
		}
	}
	return out, acc
}

func doExplodeCompound(rng *rand.Rand, rolls []int, sides int, acc []int) ([]int, []int, error) {
	out := append([]int(nil), rolls...)
	queue := append([]int(nil), rolls...)

	explosions := 0
	for len(queue) > 0 {
		v := queue[0]
		queue = queue[1:]

		if v == sides {
			explosions++
			if explosions > maxExplodeDepth {
				return nil, nil, fmt.Errorf("compound explode exceeded max depth %d", maxExplodeDepth)
			}
			newv := rng.Intn(sides) + 1
			acc = append(acc, newv)
			out = append(out, newv)
			queue = append(queue, newv)
		}
	}

	return out, acc, nil
}

//
// KEEP/DROP HELPERS
//

func keepHighest(values []int, n int) ([]int, []int) {
	if n >= len(values) {
		return append([]int(nil), values...), nil
	}
	sorted := append([]int(nil), values...)
	sort.Sort(sort.Reverse(sort.IntSlice(sorted)))
	return sorted[:n], sorted[n:]
}

func keepLowest(values []int, n int) ([]int, []int) {
	if n >= len(values) {
		return append([]int(nil), values...), nil
	}
	sorted := append([]int(nil), values...)
	sort.Ints(sorted)
	return sorted[:n], sorted[n:]
}

func dropHighest(values []int, n int) ([]int, []int) {
	if n >= len(values) {
		return nil, append([]int(nil), values...)
	}
	sorted := append([]int(nil), values...)
	sort.Sort(sort.Reverse(sort.IntSlice(sorted)))
	return sorted[n:], sorted[:n]
}

func dropLowest(values []int, n int) ([]int, []int) {
	if n >= len(values) {
		return nil, append([]int(nil), values...)
	}
	sorted := append([]int(nil), values...)
	sort.Ints(sorted)
	return sorted[n:], sorted[:n]
}
